[package]
name = "nano_url"
version = "0.1.0"
authors = ["Aza Walker <azawalker.jr@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["router", "fullstack"] }
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false, features = ["router"] }
time = { version = "0.3.51", default-features = false, features = ["wasm-bindgen"]}
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.103"
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio", "macros", "migrate"], optional = true }

[features]
default = ["web", "server"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]
# The feature that are only required for the desktop = ["dioxus/desktop"] build target should be optional and only enabled in the desktop = ["dioxus/desktop"] feature
desktop = ["dioxus/desktop"]
# The feature that are only required for the mobile = ["dioxus/mobile"] build target should be optional and only enabled in the mobile = ["dioxus/mobile"] feature
mobile = ["dioxus/mobile"]
# The feature that are only required for the server = ["dioxus/server"] build target should be optional and only enabled in the server = ["dioxus/server"] feature
server = ["dioxus/server", "dep:sqlx"]

[dev-dependencies]
dioxus-ssr = "0.7.9"
