CREATE TABLE IF NOT EXISTS urls (
  id INTEGER PRIMARY KEY,
  hash TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  redirects INTEGER NOT NULL DEFAULT 0,
  expiration DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
